### PR TITLE
Allow selected items to be controlled from redux

### PR DESCRIPTION
**Pull request by doylem**

### CODE REVIEW

**Comment by thoiberg** [comment]
@doylem Will this change break anything if the Selectable component is used without redux?

**Comment by doylem** [comment]
@thoiberg i imagine so. We've diverged from the original plugin a fair bit though as Sam did quite a bit of hacking on it to select items the way we want. I'm happy to move this to a "controlled only" state and only allow selected items to be accumulated from props... will bump semver a major number..  thoughts?

**Comment by thoiberg** [comment]
Yep I think that should be enough, provided we never need to use it outside of redux (or anything else that manages state) . I don't really know the code base but I'm wondering if using state as the fallback would work, something like 
```
newItems = this.props.selectedItems || this.state.currentItems
```

Since this is a highly specialised implementation I'm happy to just tie it into redux state.

**Review by thoiberg — APPROVED** [review]

**Comment by doylem** [comment]
It would if we explicitly checked for an empty array... lets do that anyway as it's a small n quick fallback, but yeah, i can't see a lot of cases where we'd want an uncontrolled grid. 😄 

edit: actually, no that brings us back to the original bug when we have no items at our end, but state is kept on the plugin. lets leave it as is.

**Pull request merged**
